// UI Interface Localizations for Arabic (Main Default), English, and Romanian

export const UI_STRINGS = {
  ar: {
    appTitle: 'الجنسية الرومانية',
    appSubtitle: 'دليلك المتكامل لاجتياز الاختبار الشفهي للجنسية الرومانية وتعلم الأبجدية والنطق الصحيح والقواعد والمحادثات اليومية',
    questionsBadge: '469 سؤالاً مصوراً لاختبار الجنسية الرومانية ANC',
    citizenshipSectionTitle: 'أسئلة امتحان الجنسية الرومانية (469 سؤالاً مصوراً)',
    viewAllQuestions: 'عرض جميع الأسئلة',
    questionsReadyBadge: 'سؤالاً جاهزاً ⚡',
    learningModulesSectionTitle: 'وحدات تعلم اللغة والقواعد والمحادثات',
    grammarCardTitle: 'شرح قواعد الرومانية والضمائر',
    grammarCardSubtitle: 'الأجناس وأدوات التعريف وتصريف الأفعال مع النطق الصوتي',
    grammarQuizCardTitle: 'لعبة اختبار القواعد 🎮',
    grammarQuizCardSubtitle: 'تحديات ممتعة لاختبار معرفتك بتصريف الأفعال والأدوات',
    conversationsCardTitle: 'المحادثات والحوارات اليومية 🗣️',
    conversationsCardSubtitle: 'حوارات الفندق والقطار والطوارئ والمقابلة بالصوت',
    vocabQuizCardTitle: 'اختبار المفردات والجمل 🎮',
    vocabQuizCardSubtitle: 'تحدي الكلمات والجمل الرومانية اليومية',
    aiCardTitle: 'المساعد الذكي للأسئلة المفتوحة 🤖',
    aiCardSubtitle: 'اسأل أي سؤال إضافي وتحدث مع الذكاء الاصطناعي',
    homeNav: 'الرئيسية',
    studyNav: 'المذاكرة',
    quizNav: 'الاختبارات',
    alphabetNav: 'الأبجدية الرومانية',
    alphabetQuizNav: 'لعبة النطق',
    conversationsNav: 'المحادثات اليومية',
    conversationQuizNav: 'لعبة المحادثات',
    grammarNav: 'شرح القواعد',
    grammarQuizNav: 'لعبة القواعد',
    aiNav: 'المساعد الذكي',
    studyNow: 'ابدأ المذاكرة المصورة',
    testYourself: 'اختبر نفسك في الامتحان 🏆',
    questionsCount: 'سؤال مصور',
    categoriesCount: 'تصنيفات المنهج',
    languagesCount: 'لغات المنهج (عربي/إنجليزي/روماني)',
    selectLangLabel: 'لغة واجهة التطبيق والترجمة:',
    allCategories: 'جميع التصنيفات',
    constitutionCat: 'الدستور والحكومة',
    historyCat: 'التاريخ والشخصيات',
    geographyCat: 'الجغرافيا والطبيعة',
    cultureCat: 'الثقافة والأدب',
    generalCat: 'معلومات عامة واللغة',
    showAnswer: 'عرض الإجابة والترجمة',
    modelAnswer: 'الإجابة النموذجية بالرومانية والترجمة:',
    prev: 'السابق',
    next: 'التالي',
    zoomImage: 'عرض الصورة بالكامل 🔍',
    close: 'إغلاق',
    question: 'سؤال',
    of: 'من',
    score: 'النتيجة',
    quickQuizTitle: 'اختبار سريع (10 أسئلة)',
    quickQuizDesc: 'اختبار ممارسة عشوائي وسريع',
    examQuizTitle: 'محاكاة الامتحان الرسمي (25 سؤالاً)',
    examQuizDesc: 'اختبار موقوت 20 دقيقة يحاكي اللجنة الرسمية',
    chooseCorrectAns: 'اختر الإجابة الصحيحة بالرومانية:',
    quizFinished: 'انتهى الاختبار!',
    passedExam: 'تهانينا! لقد اجتزت الاختبار بنجاح 🏆',
    failedExam: 'لم تجتز الاختبار، واصل المراجعة والمحاولة!',
    reviewWrong: 'مراجعة الأخطاء والأسئلة غير المحلولة',
    retakeQuiz: 'إعادة الاختبار',
    backHome: 'العودة للرئيسية',
    romanianText: 'الرومانية',
    arabicText: 'العربية',
    englishText: 'الإنجليزي',
    alphabetTitle: 'تعلم الأبجدية الرومانية والنطق',
    alphabetSubtitle: '31 حرفاً مع النطق الصوتي والأمثلة والجمل المترجمة بالكامل',
    alphabetGameTitle: 'لعبة نطق الأبجدية الرومانية 🎮',
    alphabetGameDesc: 'اختبر استماعك وقدرتك على تمييز الحروف والنطق الصحيح',
    conversationsTitle: 'المحادثات والحوارات اليومية 🗣️',
    conversationsSubtitle: 'حوارات رومانية مترجمة مع النطق الصوتي للمقابلة والحياة اليومية',
    conversationGameTitle: 'لعبة حوارات الحياة اليومية 🎮',
    grammarTitle: 'قواعد اللغة الرومانية والضمائر 📚',
    grammarSubtitle: 'دليل شامل لشرح الأجناس وأدوات التعريف وتصريف الأفعال مع النطق الصوتي',
    grammarQuizTitle: 'تحديات ولعبة قواعد الرومانية 🎮',
    playAudio: 'استمع للنطق 🔊',
    exampleWord: 'كلمة توضيحية:',
    exampleSentence: 'جملة توضيحية:',
    specialDiacritics: 'الحروف الرومانية الخاصة (Ă, Â, Î, Ș, Ț)',
  },
  en: {
    appTitle: 'Romanian Citizenship Prep',
    appSubtitle: 'Comprehensive guide for Romanian Citizenship oral interview, alphabet, grammar, & conversations',
    questionsBadge: '469 Visual Questions for ANC Romanian Citizenship Interview',
    citizenshipSectionTitle: 'Citizenship Exam Questions (469 Visual Qs)',
    viewAllQuestions: 'View All Questions',
    questionsReadyBadge: 'Questions Ready ⚡',
    learningModulesSectionTitle: 'Language, Grammar & Conversation Modules',
    grammarCardTitle: 'Romanian Grammar Guide & Pronouns',
    grammarCardSubtitle: 'Noun genders, articles, and verb conjugations with audio',
    grammarQuizCardTitle: 'Grammar Quiz Game 🎮',
    grammarQuizCardSubtitle: 'Fun interactive challenges to test verb conjugations & articles',
    conversationsCardTitle: 'Daily Conversations & Dialogues 🗣️',
    conversationsCardSubtitle: 'Hotel, train, emergency, and citizenship interview dialogues',
    vocabQuizCardTitle: 'Vocabulary & Phrases Quiz 🎮',
    vocabQuizCardSubtitle: 'Fun daily Romanian vocabulary & phrase challenges',
    aiCardTitle: 'AI Romanian Citizenship Tutor 🤖',
    aiCardSubtitle: 'Ask custom questions and practice oral responses with AI',
    homeNav: 'Home',
    studyNav: 'Study',
    quizNav: 'Quizzes',
    alphabetNav: 'Romanian Alphabet',
    alphabetQuizNav: 'Pronunciation Game',
    conversationsNav: 'Daily Conversations',
    conversationQuizNav: 'Conversation Game',
    grammarNav: 'Grammar Guide',
    grammarQuizNav: 'Grammar Quiz Game',
    aiNav: 'AI Tutor',
    studyNow: 'Start Illustrated Study',
    testYourself: 'Test Yourself in Exam 🏆',
    questionsCount: 'Visual Questions',
    categoriesCount: 'Categories',
    languagesCount: 'Languages (AR/EN/RO)',
    selectLangLabel: 'App & Translation Language:',
    allCategories: 'All Categories',
    constitutionCat: 'Constitution & Law',
    historyCat: 'History & Figures',
    geographyCat: 'Geography & Nature',
    cultureCat: 'Culture & Literature',
    generalCat: 'General & Language',
    showAnswer: 'Show Answer & Translation',
    modelAnswer: 'Model Romanian Answer & Translation:',
    prev: 'Previous',
    next: 'Next',
    zoomImage: 'View Full Entire Image 🔍',
    close: 'Close',
    question: 'Question',
    of: 'of',
    score: 'Score',
    quickQuizTitle: 'Quick Quiz (10 Questions)',
    quickQuizDesc: 'Fast random self-assessment quiz',
    examQuizTitle: 'Official Exam Simulation (25 Qs)',
    examQuizDesc: 'Timed 20-min official citizenship interview exam',
    chooseCorrectAns: 'Select the correct answer in Romanian:',
    quizFinished: 'Quiz Completed!',
    passedExam: 'Congratulations! You Passed the Exam 🏆',
    failedExam: 'You did not pass. Review and try again!',
    reviewWrong: 'Review Incorrect Answers',
    retakeQuiz: 'Retake Quiz',
    backHome: 'Back to Home',
    romanianText: 'Romanian',
    arabicText: 'Arabic',
    englishText: 'English',
    alphabetTitle: 'Romanian Alphabet & Pronunciation',
    alphabetSubtitle: '31 letters with native audio speech, example words, sentences, & translations',
    alphabetGameTitle: 'Alphabet Pronunciation Game 🎮',
    alphabetGameDesc: 'Fun interactive audio game to test your listening & letter recognition',
    conversationsTitle: 'Daily Conversations & Dialogues 🗣️',
    conversationsSubtitle: 'Translated Romanian dialogues with audio speech for interview & daily life',
    conversationGameTitle: 'Daily Life Conversation Game 🎮',
    grammarTitle: 'Romanian Grammar Guide & Pronouns 📚',
    grammarSubtitle: 'Comprehensive guide explaining noun genders, articles, & verb conjugations',
    grammarQuizTitle: 'Romanian Grammar Quiz Challenge 🎮',
    playAudio: 'Listen to Audio 🔊',
    exampleWord: 'Example Word:',
    exampleSentence: 'Example Sentence:',
    specialDiacritics: 'Special Romanian Diacritics (Ă, Â, Î, Ș, Ț)',
  },
  ro: {
    appTitle: 'Pregătire Cetățenia Română',
    appSubtitle: 'Ghid complet pentru interviul de cetățenie, alfabetul român, gramatică și conversații',
    questionsBadge: '469 de Întrebări Ilustrate pentru Examenul de Cetățenie ANC',
    citizenshipSectionTitle: 'Întrebări Examen Cetățenie (469 Întrebări Ilustrate)',
    viewAllQuestions: 'Vezi Toate Întrebările',
    questionsReadyBadge: 'Întrebări Pregătite ⚡',
    learningModulesSectionTitle: 'Module de Limbă, Gramatică și Dialoguri',
    grammarCardTitle: 'Ghid de Gramatică Română și Pronume',
    grammarCardSubtitle: 'Genurile substantivelor, articolele și conjugările verbelor cu audio',
    grammarQuizCardTitle: 'Joc de Testare Gramatică 🎮',
    grammarQuizCardSubtitle: 'Provocări interactive pentru testarea conjugărilor și articolelor',
    conversationsCardTitle: 'Conversații și Dialoguri Zilnice 🗣️',
    conversationsCardSubtitle: 'Dialoguri la hotel, tren, urgențe și interviu cetățenie',
    vocabQuizCardTitle: 'Test de Vocabular și Expresii 🎮',
    vocabQuizCardSubtitle: 'Provocări distractive de vocabular și expresii zilnice',
    aiCardTitle: 'Asistent AI Cetățenia Română 🤖',
    aiCardSubtitle: 'Adresează întrebări personalizate și exersează răspunsurile cu AI',
    homeNav: 'Acasă',
    studyNav: 'Studiu',
    quizNav: 'Teste',
    alphabetNav: 'Alfabetul Român',
    alphabetQuizNav: 'Joc Pronunție',
    conversationsNav: 'Conversații Zilnice',
    conversationQuizNav: 'Joc Conversații',
    grammarNav: 'Ghid Gramatică',
    grammarQuizNav: 'Joc Gramatică',
    aiNav: 'Asistent AI',
    studyNow: 'Începe Studiul Ilustrat',
    testYourself: 'Testează-te în Examen 🏆',
    questionsCount: 'Întrebări Ilustrate',
    categoriesCount: 'Categorii',
    languagesCount: 'Limbi (RO/AR/EN)',
    selectLangLabel: 'Limba Aplicației și Traducerii:',
    allCategories: 'Toate Categoriile',
    constitutionCat: 'Constituție și Drept',
    historyCat: 'Istorie și Domnitori',
    geographyCat: 'Geografie și Natură',
    cultureCat: 'Cultură și Literatură',
    generalCat: 'Limbă și Cultură Generală',
    showAnswer: 'Afișează Răspunsul și Traducerea',
    modelAnswer: 'Răspuns Model în Română și Traducere:',
    prev: 'Înapoi',
    next: 'Înainte',
    zoomImage: 'Vezi Imaginea Completă 🔍',
    close: 'Închide',
    question: 'Întrebare',
    of: 'din',
    score: 'Scor',
    quickQuizTitle: 'Test Rapid (10 Întrebări)',
    quickQuizDesc: 'Verificare rapidă a cunoștințelor',
    examQuizTitle: 'Simulare Examen Oficial (25 Întrebări)',
    examQuizDesc: 'Test cronometrat 20 min ce simulează comisia oficială',
    chooseCorrectAns: 'Alege răspunsul corect în română:',
    quizFinished: 'Test Finalizat!',
    passedExam: 'Felicitări! Ai promovat examenul 🏆',
    failedExam: 'Nu ai promovat. Revizuiește și încearcă din nou!',
    reviewWrong: 'Revizuiește Greșelile',
    retakeQuiz: 'Reia Testul',
    backHome: 'Înapoi la Pagina Principală',
    romanianText: 'Română',
    arabicText: 'Arabă',
    englishText: 'Engleză',
    alphabetTitle: 'Alfabetul Român și Pronunția',
    alphabetSubtitle: '31 de litere cu audio vocal, cuvinte exemplu, propoziții și traduceri',
    alphabetGameTitle: 'Joc de Pronunție a Alfabetului 🎮',
    alphabetGameDesc: 'Joc interactiv distractiv pentru testarea auzului și recunoașterea literelor',
    conversationsTitle: 'Conversații și Dialoguri Zilnice 🗣️',
    conversationsSubtitle: 'Dialoguri românești traduse cu audio pentru interviu și viața de zi cu zi',
    conversationGameTitle: 'Joc Conversații din Viața de Zi cu Zi 🎮',
    grammarTitle: 'Ghid de Gramatică Română și Pronume 📚',
    grammarSubtitle: 'Ghid complet ce explică genurile substantivelor, articolele și conjugările',
    grammarQuizTitle: 'Sfidarea Jocului de Gramatică Română 🎮',
    playAudio: 'Ascultă Pronunția 🔊',
    exampleWord: 'Cuvânt Exemplu:',
    exampleSentence: 'Propoziție Exemplu:',
    specialDiacritics: 'Litere Speciat Românești (Ă, Â, Î, Ș, Ț)',
  }
};

export function getQuestionText(q, lang = 'ar') {
  if (!q) return '';
  if (lang === 'en') {
    if (q.question_en && q.question_en !== q.question) return q.question_en;
    if (q.question.startsWith('Care este ')) return 'What is ' + q.question.slice(10);
    if (q.question.startsWith('Care sunt ')) return 'What are ' + q.question.slice(10);
    if (q.question.startsWith('Cine a fost ')) return 'Who was ' + q.question.slice(12);
    if (q.question.startsWith('Cine este ')) return 'Who is ' + q.question.slice(10);
    if (q.question.startsWith('Ce știți despre ')) return 'What do you know about ' + q.question.slice(16);
    if (q.question.startsWith('Enumerați ')) return 'List ' + q.question.slice(10);
    return q.question_ar || q.question;
  }
  if (lang === 'ro') {
    return q.question;
  }
  return q.question_ar || q.question;
}

export function getAnswerText(q, lang = 'ar') {
  if (!q) return '';
  if (lang === 'en') {
    if (q.answer_en && q.answer_en !== q.answer) return q.answer_en;
    return q.answer_ar || q.answer;
  }
  if (lang === 'ro') {
    return q.answer;
  }
  return q.answer_ar || q.answer;
}

export function getTranslation(item, field, lang = 'ar') {
  if (!item) return '';
  if (lang === 'en' && item[`${field}_en`]) return item[`${field}_en`];
  if (lang === 'ro' && item[`${field}_ro`]) return item[`${field}_ro`];
  if (lang === 'ro' && item[field]) return item[field];
  return item[`${field}_ar`] || item[`${field}_en`] || item[field] || '';
}
